Document "Button2" dependency of example
The "Button2Integration" example sketch has a dependency on the "Button2" library.

Because this library is only a dependency of the example, it was not specified as a dependency in the metadata. For this
reason, the user must explicitly install "Button2" before compiling the sketch. If they don't do that, compilation will
fail:

Compilation error: Button2.h: No such file or directory

It will be helpful to instruct the user to install the "Button2" dependency in the sketch comments.